services:
  wg-easy:
    environment:
      #- PORT=51821
      #- WG_HOST=acebin.privatedns.org
      - INSECURE=true
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wireguard
    networks:
      wg:
        ipv4_address: 10.0.1.2
    volumes:
      - /mnt/nvme/docker/volumes/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - 51820:51820/udp #zugriff von Internet
      - 51821:51821/tcp #zugriff auf webseite
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
networks:
  wg:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24

