version: "3.8"
services:
  wg-easy:
    environment:
      # Required:
      - LANG=de
      - WG_HOST=xxx.xxx.xxx # IP oder DynDNS von Extern erreichbar
      - PASSWORD_HASH=password
      - PORT=51821
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=192.168.1.x
      - WG_DEFAULT_DNS=192.168.0.80
      - WG_MTU=1500
      - WG_PERSISTENT_KEEPALIVE=25
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=3 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    hostname: wireguard
    volumes:
      - /home/docker-volumes/wireguard:/etc/wireguard
    ports:
      - 51823:51820/udp # Zugriff von außen -> muss am Router eingestellt werden (Port-forwarding)
      - 51821:51821/tcp # Zugriff auf Webseite
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
networks: {}
