services:
  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: piholeV6
    image: pihole/pihole:latest
    network_mode: host # DHCP-Server
    environment:
      TZ: Europe/Vienna
      FTLCONF_webserver_api_password: passwort
      FTLCONF_dns_upstreams: 193.110.81.0;185.253.5.0
    volumes:
      - /mnt/nvme/docker/volumes/pihole/etc-pihole:/etc/pihole
    cap_add:
      - NET_ADMIN #DHCP-Server
      - SYS_TIME #NTP-Client
      - SYS_NICE
    restart: unless-stopped
networks: {}
