services:
  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: piholeV6
    image: pihole/pihole:latest
    network_mode: host # DHCP-Server
    ports:
      # DNS Ports
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp # Default HTTP Port
      - 443:443/tcp
      - 67:67/udp #DHCP-Server
    environment:
      TZ: Europe/Vienna
      FTLCONF_webserver_api_password: password
      FTLCONF_misc_etc_dnsmasq_d: "true" #nach update löschen
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - /mnt/nvme/docker/volumes/pihole/etc-pihole:/etc/pihole
      - /mnt/nvme/docker/volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d #nach update löschen
    cap_add:
      - NET_ADMIN #DHCP-Server
      - SYS_TIME #NTP-Client
      - SYS_NICE
    restart: unless-stopped
networks: {}
