version: "3.8"
services:
  netalertx:
    container_name: netalertx
    hostname: netalertx
    mac_address: E4:5F:01:68:85:00
    image: jokobsk/netalertx:latest
    networks:
      macvlan1-1:
        ipv4_address: 192.168.0.200
    restart: unless-stopped
    volumes:
      - /home/docker-volumes/netalertx/config:/app/config
      - /home/docker-volumes/netalertx/db:/app/db
      - /home/docker-volumes/netalertx/log:/app/front/log
    environment:
      - TZ=Europe/Vienna
      - PORT=20211
      - LISTEN_ADDR=192.168.0.200
networks:
  macvlan1-1:
    # Name des Netzwerks innerhalb des Stacks
    external: true
